FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig.json ./

COPY packages/bot ./packages/bot
COPY packages/shared ./packages/shared

RUN npm ci

WORKDIR /app/packages/shared
RUN npm run build

WORKDIR /app/packages/bot
RUN npm run build

WORKDIR /app

CMD ["npm", "run", "start", "--workspace=@starforge/bot"]
