FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./

COPY packages/frontend ./packages/frontend
COPY packages/shared ./packages/shared

RUN npm ci

WORKDIR /app/packages/frontend

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
